name: Test Action

# Controls when the action will run. Workflow runs when a commit is pushed to
# the main branch
on:
  pull_request:
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: Aetheron/pr-close-teamwork-task@main
      with:
        task_id: 12345
        domain: stoplight.io/mocks/teamwork-dot-com/teamwork/42258910
        api_key: ${{ secrets.TEAMWORK_API_KEY }}
